### ISSUE TITLE
Insufficient margins on mobile display

### ISSUE THREAD

**Issue by htranin** [DurhamJohnAPaice/GEMTOM#1]
**Describe the bug**
The sections below the "Live Feed" button on the main page are only partially visible (text cut to the left).

**To Reproduce**
1. Go to the main page on Google Chrome on mobile
2. Scroll down to '...st Targets'
3. You can't read the beginning of each line

**Expected behavior**
The text should appear fully even on mobile browser.

**Screenshots**
![Screenshot_2024-10-01-19-21-48-597_com android chrome](https://github.com/user-attachments/assets/d8a4d168-3b5f-43c1-91dd-593452d0cb69)

**What browser are you using?**
Google Chrome on Android

**Comment by DurhamJohnAPaice** [comment]
Fixed; page should now be usable on (most) resolutions.
Congratulations on getting the first issue!
